name: llm-data-annotation
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - pyautogen==0.2.*
      - openai>=1.0.0
      - tiktoken>=0.5.0
      - requests>=2.31.0
      - python-dotenv>=1.0.0
      - pydantic>=2.0
      - pandas>=2.0.0
      - flaml>=2.1.0  # <-- just basic flaml, no [automl]
