name: llm-data-annotation
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - pyautogen==0.2.35
      - openai==1.76.0
      - tiktoken==0.9.0
      - pandas==2.2.3
      - python-dotenv==1.1.0
      - flaml==2.3.4 # <-- just basic flaml, no [automl]
      - scikit-learn==1.6.1
      - numpy==1.26.4
      - tqdm==4.67.1
      - pyyaml==6.0.1
